basePath: /
definitions:
  models.WandersteinResponse:
    properties:
      created_at:
        example: "2024-01-15T10:30:00Z"
        type: string
      id:
        example: 1
        type: integer
      name:
        example: Steiniger Pfad
        type: string
      preview_url:
        example: https://example.com/images/wanderstein1.jpg
        type: string
      unique_id:
        example: WS-2024-001
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: support@trailmarks.io
    name: API Support
    url: http://www.trailmarks.io/support
  description: API for managing Wandersteine (hiking stones)
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Trailmarks API
  version: "1.0"
paths:
  /api/wandersteine:
    get:
      consumes:
      - application/json
      description: Get all hiking stones
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.WandersteinResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all Wandersteine
      tags:
      - wandersteine
  /api/wandersteine/recent:
    get:
      consumes:
      - application/json
      description: Get the 5 most recently added hiking stones
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.WandersteinResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get recent Wandersteine
      tags:
      - wandersteine
swagger: "2.0"
